#define _POSIX_C_SOURCE 200809L
/*
 * libpeer_global.c
 *
 * Global init/shutdown for libpeer backend.
 * Provides the same symbols as dtls_srtp.c (dtls_srtp_global_init etc)
 * but uses peer_init()/peer_deinit() when USE_LIBPEER=1.
 */

#include "webrtc/dtls_srtp.h"

#include <stdio.h>

#ifdef USE_LIBPEER

#if __has_include("peer.h")
#include "peer.h"
#else
static int peer_init(){return 0;}
static void peer_deinit(){}
#endif

static int g_initialized = 0;
static char g_fingerprint_dummy[128] = "sha-256 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00";

int dtls_srtp_global_init(void)
{
    if (g_initialized) return 0;
    if (peer_init() != 0) {
        fprintf(stderr, "libpeer: peer_init() failed\n");
        return -1;
    }
    g_initialized = 1;
    printf("libpeer: initialized (mbedTLS + libsrtp + usrsctp)\n");
    printf("libpeer: local fingerprint (dummy for native compat) %s\n", g_fingerprint_dummy);
    return 0;
}

void dtls_srtp_global_shutdown(void)
{
    if (!g_initialized) return;
    peer_deinit();
    g_initialized = 0;
    printf("libpeer: deinitialized\n");
}

const char* dtls_srtp_local_fingerprint(void)
{
    /* libpeer generates fingerprint internally per PeerConnection.
     * For compatibility with native code that expects a global fingerprint,
     * return dummy. The real fingerprint is in the answer SDP generated by
     * peer_connection_create_answer().
     */
    return g_fingerprint_dummy;
}

/* Stubs for native API not used in libpeer mode - keep signatures exact */
void dtls_srtp_set_expected_fingerprint(DtlsSrtp *session, const char *fingerprint){(void)session;(void)fingerprint;}
DtlsSrtp *dtls_srtp_session_create(const DtlsSrtpCallbacks *callbacks){(void)callbacks;return NULL;}
void dtls_srtp_session_destroy(DtlsSrtp *session){(void)session;}
void dtls_srtp_on_udp(DtlsSrtp *session, const uint8_t *packet, size_t len){(void)session;(void)packet;(void)len;}
void dtls_srtp_tick(DtlsSrtp *session){(void)session;}
int dtls_srtp_next_timeout_ms(const DtlsSrtp *session){(void)session;return -1;}
int dtls_srtp_send_rtp(DtlsSrtp *session, uint8_t *pkt, size_t *len){(void)session;(void)pkt;(void)len;return -1;}
int dtls_srtp_send_rtcp(DtlsSrtp *session, uint8_t *pkt, size_t *len){(void)session;(void)pkt;(void)len;return -1;}
int dtls_srtp_unprotect_rtcp(DtlsSrtp *session, uint8_t *pkt, size_t *len){(void)session;(void)pkt;(void)len;return -1;}
void dtls_srtp_close(DtlsSrtp *session){(void)session;}

#else /* !USE_LIBPEER */

/* When not using libpeer, the real implementation is in dtls_srtp.c,
 * so this file should not be compiled. Provide stubs to avoid duplicate
 * symbols if both files are accidentally linked.
 */

#endif
