/*
 * embed_assets.c
 *
 * Build time helper: embed text files as C byte arrays so the single
 * camstream binary can serve the web page with no web root on disk.
 *
 * usage:
 *   embed_assets <output.h> <guard> <var1> <file1> [<var2> <file2> ...]
 *
 * Emits:
 *   #ifndef <guard>
 *   #define <guard>
 *   static const unsigned char <var1>[] = { 0x.., ..., 0x00 };
 *   ...
 *   #endif
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static void emit_file(FILE *out, const char *var, const char *path)
{
    FILE *in = fopen(path, "rb");

    if (in == NULL) {
        fprintf(stderr, "embed_assets: cannot open %s\n", path);
        exit(1);
    }

    fprintf(out, "static const unsigned char %s[] = {\n", var);

    int column = 0;
    int byte;

    while ((byte = fgetc(in)) != EOF) {
        if (column == 0) {
            fprintf(out, "    ");
        }

        fprintf(out, "0x%02x,", (unsigned) byte);
        column++;

        if (column == 16) {
            fprintf(out, "\n");
            column = 0;
        }
    }

    /*
     * NUL terminate so the arrays can be used as C strings.
     */
    if (column != 0) {
        fprintf(out, " ");
    }

    fprintf(out, "0x00\n};\n\n");
    fclose(in);
}

int main(int argc, char **argv)
{
    if (argc < 5 || (argc - 3) % 2 != 0) {
        fprintf(stderr,
                "usage: %s <output.h> <guard> <var> <file> [<var> <file> ...]\n",
                argv[0]);
        return 2;
    }

    FILE *out = fopen(argv[1], "wb");

    if (out == NULL) {
        fprintf(stderr, "embed_assets: cannot write %s\n", argv[1]);
        return 1;
    }

    fprintf(out, "/*\n * Generated by tools/embed_assets.c from:\n");

    for (int i = 3; i < argc; i += 2) {
        fprintf(out, " *   %s\n", argv[i + 1]);
    }

    fprintf(out, " */\n#ifndef %s\n#define %s\n\n", argv[2], argv[2]);

    for (int i = 3; i < argc; i += 2) {
        emit_file(out, argv[i], argv[i + 1]);
    }

    fprintf(out, "#endif /* %s */\n", argv[2]);

    fclose(out);

    return 0;
}
